### PR TITLE
Revise the link text displayed by the plugin

### PR DESCRIPTION
**Pull request by stichbury**
I've made a slight change to the text that's displayed by the plugin. I think it would also help to bold it or make it slightly larger so it is very easy to spot it.

For bonus points, I'd _really_ like a small coffee cup icon too if that's at all possible? Inline next to the text? I think it would help stand out to the user (they'll get used to looking for it and thus being able to easily find and click through). WDYT?

@maartenbreddels

### CODE REVIEW

**Comment by stichbury** [comment]
@maartenbreddels @itsjoeoui Just wanted to highlight this PR to you for when you're able to take a look.

I would like to revise the copy slightly that is displayed if possible. I've a draft PR which shows how it looks right now ([see here for an example](https://vizro--569.org.readthedocs.build/en/569/pages/user-guides/card-button/#cards)). I think it's getting lost and needs to stand out a bit more.

image

I'd like instead for the copy to be bold and change the wording if that's OK. I also think it would look neat with your logo.
What about this?

image

[Example here where I'm pointing to an existing project rather than using the plugin](https://vizro--569.org.readthedocs.build/en/569/pages/user-guides/card-button/#place-an-image-on-a-card)

* I have changed the text in the PR here
* I haven't changed the bolding or added the cup. I'm not sure how you'd prefer to do that. WDYT?


cc @maxschulz-COL

**Comment by maartenbreddels** [comment]
Hi Jo,

I think both are a good idea. I've pushed the changes on top of this PR, let me know what you think?

Regards,

Maarten


Closes #1

**Comment by stichbury** [comment]
Thanks for this! I'm just working out how to test it but I like the customisation option to change the text! Will let you know when review is complete.

**Comment by stichbury** [comment]
OK tested, thanks to Max, and all is good: I'm happy for you to merge this when you're happy.

Screenshot 2024-08-14 at 18 07 50

**Comment by maartenbreddels** [comment]
Great, thanks for helping with this Jo and Max!

**Pull request merged**
